### ISSUE TITLE
When on fastest speed clicking to move a party sets the speed to 1x

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#108]
Fix pls

**Comment by DiMiGi** [comment]
This is a normal behaviour. I tested it without mods in a brand new campaign and the game set the speed to 1x when the party was going on 2x (fastest) speed after clicking on map.
![ezgif-3-1502e5a63c3f](https://user-images.githubusercontent.com/23215672/99200081-0c44cf80-2782-11eb-93bf-141dabae2e05.gif)

**Comment by garrettluskey** [comment]
Although this is normal behavior, this is not what we want for the mod. Instead of the time being controlled by party movement it should be only controlled by the players.
