### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#125]
The readme is out of date and should be updated and beautified.

**Comment by kikoncuo** [comment]
This is key, the mod looks dead until you look at the issues and code, I'm sure most people don't go that far.
Besides right now new people just don't know what features are available!

**Comment by kamyabnazari** [comment]
I would like to change the README.md, on first sight as @kikoncuo mentioned, it is not really encoureging looking at the GitHub page. It really looks dead, until you try to look at the milestones.

For me to be able to fill in the right informations, i would like your help, i have created the fork already {Fork](https://github.com/Kamyabnz/BannerlordCoop). What features are already implemented ?

**Comment by garrettluskey** [comment]
Resolved
