### ISSUE TITLE
Building Sync

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#183]
This is essentially town upgrades

Building updates need to be synchronized via RPC and value persistence. Look into what other sync might be needed and implement.

See https://bannerlord-coop-team.github.io/BannerlordCoop/overview/syncing.html

**Comment by Anziverov** [comment]
Will be storing here a list of potential places to be looked at
1. TaleWorlds.CampaignSystem.Town (DailyTick->TickCurrentBuilding)
2. Helpers.BuildingHelper
3. TaleWorlds.CampaignSystem.SandBox.GameComponents.DefaultBuildingConstructionModel

**Comment by garrettluskey** [comment]
Will remake using new issue format
