### ISSUE TITLE
Clan/Family data not transfered to client

### ISSUE THREAD

**Issue by Nijco** [araex/BannerlordCoop#186]
See Title. 
-> Causes crash when client tries to assess the clan menu.

**Comment by EgardA** [comment]
This does not cause a crash anymore, there are however two parties appearing in the "Parties" tab in the Clan Menu.

**Comment by EgardA** [comment]
I've confirmed that it is the Clan having multiple lordPartyComponents in WarPartyComponents being the issue (fixable using RemoveWarPartyInternal) 

`[CommandLineFunctionality.CommandLineArgumentFunction("remove_wpc", sTestGroupName)]
        public static string RemovePartyComps(List<string> parameters)
        {
            typeof(Clan).GetMethod("RemoveWarPartyInternal", BindingFlags.Instance | BindingFlags.NonPublic)
           .Invoke(MobileParty.MainParty.ActualClan, new object[] { MobileParty.MainParty.ActualClan.WarPartyComponents.FirstOrDefault() });
            return "end";
        }`

I can't tell where it is being duplicated. Could it be that the WarPartyComponent from the game it loads initially following over?

There also appears to be an issue with the Clients Clan having 0 WarPartyComponents on the Server

**Comment by garrettluskey** [comment]
Issue now contained in #248
