### ISSUE TITLE
Provide a way to trigger a synchronized RPC with large binary payloads

### ISSUE THREAD

**Issue by araex** [araex/BannerlordCoop#19]
RPC through persistence are very limited in the amount of data that can be packed into the event arguments itself. We need a way to send arbitrary data amounts through a second channel and delay the RPC until all client received it.

**Comment by garrettluskey** [comment]
Merged so closing

**Comment by araex** [comment]
The object store that was merged is not integrated into the RPC generated by the auto patcher. I'm still working on that
