### ISSUE TITLE
Create Hideout Managed

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#237]
Create a new class for hideouts similar to https://github.com/Bannerlord-Coop-Team/BannerlordCoop/blob/mobile-party-spawn-sync/source/Coop/Mod/GameSync/Party/MobilePartyManaged.cs#L113.

Hideouts must only spawn on server, so disable spawning on client using harmony.

When a client connects transfer all hideouts from server or when server spawns hideouts transfer to all clients.

**Comment by thomasDelaporte** [comment]
@garrettluskey Part of the basic synchronization was done on PR #244.
