### ISSUE TITLE
Server fire ServerPlaying too early after ServerSendingWorldData

### ISSUE THREAD

**Issue by evorios** [araex/BannerlordCoop#24]
`EConnectionState.ServerPlaying` triggered when player watch background image after he loaded world data.
At this moment server think that player already play.
This is fraught with errors when the server tries to send some rpc method to the client.

https://github.com/Bannerlord-Coop-Team/BannerlordCoop/blob/f3b388c1669f386b3f4d2e74ae5fc3e6f5fbf110/source/Network/Infrastructure/ConnectionServer.cs#L47-L54

**Comment by garrettluskey** [comment]
Merged so closing
