### ISSUE TITLE
Client Issues Projectiles and Projectile Damages

### ISSUE THREAD

**Issue by masesk** [araex/BannerlordCoop#268]
Entry:
* Missions Server
Exit:
* Disable projectiles being created on the client
* Clients sends the disable projectile information to the server
* Server "verifies" it (now it does nothing) and returns it back to each client
* Server data creates a custom projectile for all clients

**Comment by garrettluskey** [comment]
This will now be client based, so when a controlled agent shoots an arrow. The event is broadcasted from that client to all others.
