### ISSUE TITLE
Dynamic Serialize Hero Class

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#279]
Use the new DynamicModelGenerator to serialize the Hero class.

Exclude any fields that do not exist in the old HeroSerializer class.

Large classes like CharacterObject, PartyBelongedTo, Father, Mother, etc can be stubbed to a surrogate.

See DynamicModelGeneratorTests

**Design Decision**
Creating delegates for data classes like ItemObject was very time consuming. So instead creating a serializer across all fields was easier than getting 20 fields via reflection. However, note that dynamic serialization can be more dangerous.

**Design**
[Dynamic Serializer Class Diagram](https://drive.google.com/file/d/1MKMqLBkiq_wkQih310NSOqgNWaB7jMtB/view?usp=sharing)

**Definition of Done**
- [ ] A serializer is implemented for the Hero class
- [ ] Test exists verifying that the Hero type is serializable

**Comment by thomasDelaporte** [comment]
@garrettluskey Do you have a plan for how to test the game items without being in the game? I would have to create a "Hero" first.
