### ISSUE TITLE
Make CreateDynamicSerializer More Robust

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#285]
This method should ensure all exclude fields are used.

Throw error if it does not use all excluded fields and add unused fields to the exception message.

**Definition of Done**
- [ ] Tests exist for all cases of excludes (null, uses all, doesn't use all)

**Comment by thomasDelaporte** [comment]
@garrettluskey I modified the method to throw an exception in case there are fields that are not used in the exclusion. 
I had to rewrite the code around it, hoping it won't cause any other problems.
