### ISSUE TITLE
Sync MobileParty

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#30]
MobileParty interactions need to be synchronized via RPC and value persistence. Look into what other sync might be needed and implement.

Sync the following in the MobileParty class
_currentSettlement
_attachedTo
_besiegerCamp
_army
_actualClan
_partyTradeGold
CustomName
Scout
Quartermaster
Engineer
Surgeon

This will also include the PartyBase class as they are very coupled.

See https://bannerlord-coop-team.github.io/BannerlordCoop/overview/syncing.html

**Comment by thomasDelaporte** [comment]
@garrettluskey Is it possible to provide a more elaborate list of everything that needs to be synchronized outside of the MobileParty movement?

**Comment by garrettluskey** [comment]
Sync the following in the MobileParty class
_currentSettlement
_attachedTo
_besiegerCamp
_army
_actualClan
_partyTradeGold
CustomName
Scout
Quartermaster
Engineer
Surgeon
