### ISSUE TITLE
Investigate synchronization with MBObjectManager

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#31]
How can we verify that the ID's for each object is the same across all clients?

**Comment by evorios** [comment]
Any problems?
I thought that we manually create each object with a given `MBGUID`. And then, when passing rpc-methods, we use the `MBGUID` to search for the objects.

**Comment by garrettluskey** [comment]
`MBGUID` is assigned through MBObjectManager. We will have to create a hook for creating objects. I don't see any issues with hooking. This issue is for discussion

**Comment by araex** [comment]
In regards to patching `MBObjectManager.CreateObject`: https://github.com/pardeike/Harmony/issues/320 . It appears that may not be possible.

So we will have to patch all sites calling MBObjectManager.CreateObject instead and deal with it that way.

**Comment by garrettluskey** [comment]
We are instead mapping MBGuid manually.
