### ISSUE TITLE
Slowing down time to a fraction of 1x could be irritating to someone else

### ISSUE THREAD

**Issue by Spartan3663** [araex/BannerlordCoop#34]
If Player 1 is in battle and Player 2 has to travel at a low fraction, it could mean Player 2 actually cannot get anything done.

A possible solution could be to have the slowed time be a variable that the players can agree on beforehand, that way it's not out of the players' control and will not be irritating.

**Comment by HenrikPerssonGames** [comment]
Yes a custom value could be a nice solution (1x, 3x, 5x, etc.) 
The current solution with slowing down time is in my mind the most viable since other suggested solutions fully locks the player away from the task he or she is currently doing!

**Comment by garrettluskey** [comment]
Fraction of 1x may not be possible with engine or something. We can balance after V1
