### ISSUE TITLE
Create a way to load mod assembly dynamically

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#35]
We want a way to load the mod while the game is still running so we do not have to restart every time we compile a bug fix or new change. Load mod in separate mod using a new AppDomain and unload it every time it detects a DLL change in the loaded mod.

**Acceptance Criteria**
- Every time a new build is compiled, the build assemblies are reloaded
- Build is loaded from build destination or copied into game folder and loaded there
- Game does not crash with any mod related exception

**Comment by araex** [comment]
I use the [Rider IDE](https://www.jetbrains.com/rider/) which is able to recompile & hot swap DLLs while debugging. This feature does have some sever limitations though, you cannot change the memory layout for example. Visual Studio should be able to do that as well, but i haven't tried it myself.

I'm not sure if we can get the engine to do that for us. What we maybe could do is implement some kind of parent mod that does not change and internally hosts our swappable mods. Or how would you approach that?

**Comment by garrettluskey** [comment]
My idea was to have a base mod that hot swaps for us.
