### ISSUE TITLE
Create CharacterPerkBinaryPackage

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#402]
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

Create CharacterPerkBinaryPackage and associated unit test.

This binary package will be different from the others. All that needs to be stored is the StringId inheritied by MBObjectBase.

Store the StringId in a string field and resolve on unpack using MBObjectManager.Instance.GetObject({Stored StringId}).

## Intended Design

N/A

## Location

Work in a new branch based from [taverns-serialization](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/tree/taverns-serialization)

## Related Issues

Blocked by
- #408

## Requirements

N/A

## Additional information

See [BasicCultureObjectBinaryPackage](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/blob/taverns-serialization/source/GameInterface/Serialization/Impl/BasicCultureObjectBinaryPackage.cs) and it's [test](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/blob/taverns-serialization/source/GameInterface.Tests/Serialization/SerializerTests/BasicCultureObjectSerializerTest.cs)

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

**Comment by EgardA** [comment]
Can't find CharacterPerk but I can find PerkObject which I took this as meaning instead.

Just noticed that there is both a PerkObject and CharacterPerk in issues but only finding PerkObject in files

**Comment by WakooMan** [comment]
This issue should be closed because CharacterPerk is renamed to PerkObject.
