### ISSUE TITLE
Refactor NetworkAgentRegistry

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#432]
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

`NetworkAgentRegistry` requires a new dictionary or hashset for player agents. This will be used by the method `IsNetworkAgent` and then by `AgentInteractionPatch`.

Currently the way this works is any controlled agent even not directly player controlled returns true for `IsNetworkAgent`.

Create another extension method called `IsPlayerAgent` that returns true if the given agent is directly controlled by any player.

## Intended Design

N/A

## Location

Branch from taverns-vertical slice and merge back when complete.

## Related Issues

N/A

## Requirements

N/A

## Additional information

N/A

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

**Comment by Ciel1996** [comment]
I could work on this. Could somebody assign me, please?
