### ISSUE TITLE
Fix Board Games

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#433]
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

Add robustness for forfeiting when other player crashes.

Create some logging for packet sending and receiving (maybe in a file).

If needed @garrettluskey can add server logging.

It seems that message sending or receiving is now broken.

## Intended Design

N/A

## Location

N/A

## Related Issues

N/A

## Requirements

N/A

## Additional information

N/A

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

**Comment by EgardA** [comment]
Mostly fixed, will add logging as per needed later.
