### ISSUE TITLE
Find out why Issues are not being closed with PRs

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#445]
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

Currently Github is not closing issues with PRs. I.E #444 
#443 had to be closed manually and we want this to be automated.

Find the reason for this and fix if possible.

Add cause to the comments below.

## Intended Design

N/A

## Location

N/A

## Related Issues

N/A

## Requirements

N/A

## Additional information

N/A

## Definition of Done
- [ ] Comment describing problem.

**Comment by EgardA** [comment]
This is due to the PR's not being on the default branch, odd from Github's side..
