### ISSUE TITLE
Coop - Replace NLog to Serilog

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#447]
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

Apparently Serilog is a better logger. Replace the current NLog library with Serilog.

Remove all NLog references and update any NLog logging with Serilog.

## Intended Design

N/A

## Location

Create a branch from `develop`.

## Related Issues

N/A

## Requirements

N/A

## Additional information

N/A

## Definition of Done
- [ ] No References exist of NLog
- [ ] All current NLog logging is updated with Serilog

**Comment by SamantaTarun** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by smudge202** [comment]
FYI @tarunsamanta2k20 , I may have gotten confused here - I picked up #446 and didn't realise there were two separate issues for this; I'm also not sure what the difference is between "Coop" and "Missions", so I just made a blanket change: https://github.com/Bannerlord-Coop-Team/BannerlordCoop/pull/452

**Comment by garrettluskey** [comment]
"Coop" is the server/client logic for the Map view. These consist of 2 projects, "Coop" and "Coop.Core"
