### ISSUE TITLE
Move CompatabilityInfo to GameInterface

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#456]
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

Move CompatibilityInfo.cs and assosiated test (CompatibilityInfo_Test) to the GameInterface csproject and respective test project.
Refactor CompatibilityInfo Serialize and Deserialize to use the common BinaryFormatterSerializer.

## Intended Design

N/A

## Location

Create a branch from `taverns-vertical-slice`

## Related Issues

N/A

## Requirements

N/A

## Additional information

N/A

## Definition of Done
- [x] Class level comments exist for all new classes.
- [x] XUnit tests exist for every method that does not require the game to be ran.

**Comment by zzzzzzzzott** [comment]
Resolved by #461
