### ISSUE TITLE
Create random weapon and armor agent spawn utility

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#471]
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

For Arena, the player should spawn with random armor. In `CoopArenaController`, create a new method called `CreateRandomEquipment` that returns a new Equipment object with random weapon and armor.

## Intended Design

N/A

## Location

Create a branch based from `arena-vertical-slice`
This will be located somewhere in the TestSpawnService (#470)

## Related Issues

Blocked by
- #470 

## Requirements

N/A

## Additional information

N/A

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

**Comment by phong-nnguyen** [comment]
Someone assign me this, thank you in advance!
