### ISSUE TITLE
Deploy Intro-Server to Azure

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#475]
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

We want to use Azure for deployment of the Intro-Server.

Work with or be @smudge202 - "[I have some Free Azure points we can use]".

## Intended Design

N/A

## Location

Microsoft Azure

## Related Issues

N/A

## Requirements

N/A

## Additional information

N/A

## Definition of Done
- [ ] V1.1 Intro-Server is deployed and running on Azure
- [ ] Intro-Server IP secret is updated

**Comment by Ciel1996** [comment]
Any thoughts if the server should be deployed via VM or web-service, the latter via docker image?

**Comment by garrettluskey** [comment]
It would be fairly straight forward to dockerize. We could also build it on the server itself. I don't have strong opinions on either but docker is likely the better solution

**Comment by Ciel1996** [comment]
Has anyone already started dockerizing it? I've seen an issue (#260) on this, but it was last updated 7 months ago.

**Comment by garrettluskey** [comment]
Not going to use azure for the moment
