### ISSUE TITLE
Create Issue Template For Bannerlord-Coop-Issues

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#482]
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

Add an Issue Reporting template for the [issues repo](https://github.com/Bannerlord-Coop-Team/Bannerlord-Coop-Issues).

## Intended Design

N/A

## Location

Create a PR in https://github.com/Bannerlord-Coop-Team/Bannerlord-Coop-Issues with a Issue template

## Related Issues

N/A

## Requirements

N/A

## Additional information

N/A

## Definition of Done
- [x] New Issue Template exists for https://github.com/Bannerlord-Coop-Team/Bannerlord-Coop-Issues

**Comment by EgardA** [comment]
Did a basic issue template a while back that I added to the issues repo.

**Comment by garrettluskey** [comment]
Move that into a folder structure similar to https://github.com/Bannerlord-Coop-Team/BannerlordCoop/tree/development/.github/ISSUE_TEMPLATE @EgardA
