### ISSUE TITLE
Create GameExited Event

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#486]
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

Create a new `public readonly struct GameExited : IEvent`. This class does not require any data.

Create a new [Harmony patch](https://harmony.pardeike.net/articles/patching-prefix.html) for when the game is exited. Likely for `MapScreen.OnExit()`.

Create a test for this patch

See `CharacterCreationPatch.cs` as an example

## Intended Design

N/A

## Location

The event and patch class in their respective folders should be under `GameInterface/Services/GameState`
The test should be under a new folder called `Patches` in the `GameInterface.Test` project.

Make a new branch based from `development`

## Related Issues

Blocked by
- #289

## Requirements

N/A

## Additional information

See the [Harmony Docs](https://harmony.pardeike.net/articles/intro.html) for more info on how to use Harmony

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

**Comment by samuelzurowski** [comment]
Hey There Looks like i was able to get this to work. I'm working on this task now looking to make a test now
![image](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/assets/34222183/08b37795-9228-4896-b5f7-d07ac62a1133)
