### ISSUE TITLE
Sometime Sitting Crashes Others Game

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#489]
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

On the taverns-vertical-slice branch when someone sat down everyone crashed. This was after they opened the dialogue menu while either sitting or standing. After trying to sit down again all connected clients crashed.

This may not be an issue now since dialogue is disabled between players.

Find out why this could happen.

## Intended Design

N/A

## Location

On the taverns-vertical-slice branch

## Related Issues

N/A

## Requirements

N/A

## Additional information

N/A

## Definition of Done
- [ ] All attempts to replicate are exhausted or replication of issue occurs and is documented.

**Comment by EgardA** [comment]
I am not able to replicate this on development branch

**Comment by EgardA** [comment]
Not able to replicate, only issue I can see with this is that the player sometimes get stuck in the sitting animation, not optimal but no deal breaker. Closed for now.
