### ISSUE TITLE
Post-build options and .editorConfig cause issues.

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#5]
Normal suggestions turn to errors and I had to remove post-build options to get the project building.

**Comment by araex** [comment]
The post-build step requires a valid path to the modules directory in config.json in order to install the mod on build. Is there a better way to do this?

**Comment by araex** [comment]
Naming rule severity is dropped to `suggestion` with b383b8f.

**Comment by garrettluskey** [comment]
The suggestions turning to errors is a big with visual studio. I'll take a deeper look later today

**Comment by garrettluskey** [comment]
I recommend adding that file to the gitignore until it is fixed on their end
