### ISSUE TITLE
Properly Remove Agent IDs from Registry when a user disconnects or their agents die

### ISSUE THREAD

**Issue by masesk** [araex/BannerlordCoop#511]
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description
1. Ensure that the agents of the client (the client or their AIs) that die are removed from registry. Informed all the clients of the agent dying so they can remove it too.
2. Ensure when a death message is received, the agents are removed from registry.
3. When disconnected, remove the agents from registry and remove the client.

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

**Comment by garrettluskey** [comment]
From testing this seems fixed
