### ISSUE TITLE
Determine Cause of Connection Issues

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#533]
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

Sometimes the agent doesn't spawn for some clients. Maybe add retries for NAT punch?
Sometimes on the `arena-vertical-slice` branch, the movement breaks.

Find out why this occurs.

Some good classes to start looking at would be
- MovementHandler
- MissionModule

## Intended Design

N/A

## Location

Create a new branch based from `arena-vertical-slice`

## Related Issues

#492 may fix the issue

## Requirements

N/A

## Additional information

N/A

## Definition of Done
- [ ] A new issue exists with instructions on how to fix the issue or this issue is closed with a descriptive comment

**Comment by EgardA** [comment]
Is this the SocketException or was that an additional issue?

**Comment by garrettluskey** [comment]
SocketException was due to a not fully connected client sending messages

This is likely due to strict or moderate NAT
