### ISSUE TITLE
Transfer Agent MissionEquipment

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#537]
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

When a new item is picked up, the Hero Equipment becomes stale. Instead of sending the hero's equipment, transfer the agents MissionEquipment.

## Intended Design

N/A

## Location

Create a new branch from `arena-vertical-slice`
Replace `Equipment` in `NetworkMissionJoinInfo` with `MissionEquipment`

## Related Issues

N/A

## Requirements

N/A

## Additional information

N/A

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

**Comment by EgardA** [comment]
Did this differently by forcing the Equipment to update internal instead which saves us having to send the mission equipment as that would just be additional data as Equipment would still be needed.
