### ISSUE TITLE
Arena Client Intermittently Doesn't Transfer

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#538]
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

Sometimes one client can see the other client while the other client does not see the other.

Investigate why this is happening and create a new issue or provide a solution.

## Intended Design

N/A

## Location

N/A

## Related Issues

N/A

## Requirements

N/A

## Additional information

N/A

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

**Comment by EgardA** [comment]
Have not been able to replicate this lately
