### ISSUE TITLE
Sync health on join in battles

### ISSUE THREAD

**Issue by EgardA** [araex/BannerlordCoop#540]
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

Health on join is not synced, joining when a player is damage will result in desynced deaths.

## Intended Design

Synced deaths and health.

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

**Comment by garrettluskey** [comment]
There is still the issue of when the player is being transferred and a damage event happens to the transferring player. That is covered by #502
