### ISSUE TITLE
Add Popup Message for Server Unreachable

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#562]
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

Currently when trying to join the arena or tavern when the P2P server is offline or the user is having connection issues there is no feedback.

When the server is unreachable, show a popup saying the server is unreachable.

## Intended Design

N/A

## Location

Create a branch from `arena-vertical-slice`

## Related Issues

N/A

## Requirements

N/A

## Additional information

N/A

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

**Comment by EgardA** [comment]
The disconnected one covers this too, same message though
