### ISSUE TITLE
Timeout in ServerConfiguration is not the same on client.

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#58]
While debugging I was still getting timeouts on the client-side even with a 500-second timeout.

**Comment by araex** [comment]
Can be looked at without going too deep into the mod. Entry point for setting up a connection is `CoopClient.Connect` and `CoopServer.OnClientConnected` on the server side. I assume the timeout is not set on the clients connection implementation `LiteNetManagerClient `.
