### ISSUE TITLE
Absolute paths to game files

### ISSUE THREAD

**Issue by araex** [araex/BannerlordCoop#6]
The post-build step requires a valid path to the modules directory in config.json in order to install the mod on build. Is there a better way to do this?

_Originally posted by @araex in https://github.com/Bannerlord-Coop-Team/BannerlordCoop/issues/5#issuecomment-629992794_

There's a general issue here with hard coded path to the games assemblies, for example in [commit aa95d1e](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/commit/aa95d1ee6901f225f8212fdb16f13d25edf22df9#diff-f6b65d33d0abb906649d7373d4018b83R38). I think the path to the game should be configured once and everything should be relative from there. The config.json that i used in my post build step was intended for that. Not sure on how to get visual studio to pick that up though.

**Comment by araex** [comment]
@garrettluskey do you know of a way to configure visual studio to read an assembly path from a file?

**Comment by garrettluskey** [comment]
Looking into this, I prefer the config way. There is some verbosity missing from the PowerShell file to assist with debugging why it does not work. I get error code 1 quite a bit.

**Comment by araex** [comment]
Could it be that a game instance is still running and the files cannot be overridden because of this? I'll try to add some better error reporting to the powershell script.

**Comment by garrettluskey** [comment]
It doesn't appear to have anything to do with the game running. I'm sure that would be a problem but not currently the one I'm experiencing.

**Comment by araex** [comment]
It appears to be an issue with whitespace in the path not being properly escaped when passing it from Visual Studio to the powershell script.

**Comment by araex** [comment]
Fixed by @evorios with f3b388c1669f386b3f4d2e74ae5fc3e6f5fbf110 .
