### ISSUE TITLE
Add Party Postion to PartyBehaviorUpdateData

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#641]
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

The party position should be updated as well to keep the state more consistent with the server.

Add party position with `PartyBehaviorUpdateData`
Update party position on receive of `MobilePartyBehaviorHandler.Handle_UpdatePartyBehavior`
`PartyBehaviorPatch.SetAiBehavior` will also need to have functionality added to update the party position

## Intended Design

N/A

## Location

Create a new branch from `development`

## Related Issues

N/A

## Requirements

N/A

## Additional information

N/A

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

**Comment by EgardA** [comment]
duplicate
