### ISSUE TITLE
Strange Camera Movement

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#661]
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

When trying to move the camera, it jitters quite a bit. I think it is an issue with when the camera is changed after the client changes to the newly created hero

## Intended Design

N/A

## Location

Create a new branch based from `development`

## Related Issues

N/A

## Requirements

N/A

## Additional information

N/A

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

**Comment by EgardA** [comment]
The current work-around for this is to open any menu, am yet to find a fix for this.
