### ISSUE TITLE
Incorrect Banner Transfer

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#682]
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

When a new player is transferred the banner (for the flag and under the player's party) is a default banner.

What I think is happening here is either there is something wrong with the [serializer](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/blob/development/source/GameInterface/Serialization/External/BannerBinaryPackage.cs) or the [StringId for the new clan](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/blob/development/source/GameInterface/Serialization/External/ClanBinaryPackage.cs#L55) already exists on the server

Find the cause why this is happening and fix this issue.
You can also create a new issue with a more in depth explanation on what is going wrong

## Intended Design

N/A

## Location

Create a new branch based off main

## Related Issues

N/A

## Requirements

N/A

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

**Comment by EgardA** [comment]
This issue is probably related to #685
