### ISSUE TITLE
Heroes In Same Faction

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#685]
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

All newly created hero's with the same culture seem to all be in the same faction

We want all player parties to be in separate clans or factions

Either create an issue describing this in more detail and a solution to implement or resolve this issue

Possible issue with [clan deserialization](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/blob/development/source/GameInterface/Serialization/External/ClanBinaryPackage.cs#L55)

## Intended Design

N/A

## Location

Create a new branch based from development

## Related Issues

N/A

## Requirements

N/A

## Additional information

N/A

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

**Comment by EgardA** [comment]
This seems to be due to the StringId, of every client clan being "player_faction".

The way to go is probably to create a new clan when a message of create new clan has the value of "player_faction".

Perhaps a map of every NetPeer and the "new" clanId?
