### ISSUE TITLE
Town Enter/Town Leave Crash

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#686]
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

Leaving or entering castles/settlements crashes the client.

Find why this is and resolve the issue

## Intended Design

N/A

## Location

Create a new branch from development

## Related Issues

N/A

## Requirements

N/A

## Additional information

N/A

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

**Comment by EgardA** [comment]
game_menu_town_outside_on_init gets called on leave (seems to be a tick method?), which it should not as this method is the town menu.

A simple solution to this would be to keep a bool on every client if they have sent a request to enter/exit a settlement. If they according to that are not in a settlement, patch a return on above method
