### ISSUE TITLE
Recalling Brother Crash

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#689]
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

Recalling your brother in the clan screen crashes the client.

Either sync this call or disable if not feasible

## Intended Design

N/A

## Location

Create a new branch based from development

## Related Issues

- #680

## Requirements

N/A

## Additional information

N/A

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

**Comment by EgardA** [comment]
This does not crash me nor is this an actual issue at the moment as the "Brother" is another player thus should not be there.
See #685
