### ISSUE TITLE
Party Movement - Arrow Key Sync

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#691]
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

Apparently you can use the arrow keys on the keyboard to move your party.

Just disabling this is also valid, see MapHotKeyCategory.RegisterGameKeys has arrow key controls

Sync these position updates with the server

## Intended Design

N/A

## Location

Create a branch based from [development](https://github.com/Bannerlord-Coop-Team/BannerlordCoop)

## Related Issues

N/A

## Requirements

N/A

## Additional information

N/A

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

**Comment by EgardA** [comment]
This already seems synced with the normal positioning?

**Comment by WakooMan** [comment]
This seems to be synced, but a little bit buggy. Going to fix it.
