### ISSUE TITLE
Party Speed Sync

### ISSUE THREAD

**Issue by EgardA** [araex/BannerlordCoop#725]
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

Currently, the client and server does not agree on a party speed all the time which I believe results in choppy movement as the server corrects the client position.

From my observations this issue on exists on player parties (maybe only your own even?). 

Investigate and sync to the extent required.

## Location

Create a branch based from [development](https://github.com/Bannerlord-Coop-Team/BannerlordCoop)

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

**Comment by samuelzurowski** [comment]
Going to attempt to: 
- patch the setter of the speed for player parties
- and let the server change the speed of any player party.
