### ISSUE TITLE
Village Sync

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#727]
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

- Disable Village.DailyTick for only the client
Create sync events for the following property setter methods
- `VillageState`
- `Bound`
- `TradeBound`
- `Hearth`
- `TradeTaxAccumulated`
- `LastDemandSatisfiedTime`

## Intended Design

Create a copy of [GameInterface Service Template](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/tree/castle-exit-fix/source/GameInterface/Services/Template) for Villages if one does not already exist.

Use that template format to create Patches and Handlers for updating the data above

Create a copy of [Server Service Template](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/tree/castle-exit-fix/source/Coop.Core/Server/Services/Template) for handling server related functionality
Create a copy of [Client Service Template](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/tree/castle-exit-fix/source/Coop.Core/Client/Services/Template) for handling client related functionality

Create an integration test using the [integration test template](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/tree/castle-exit-fix/source/Coop.IntegrationTests/Template)

## Location

Create a branch based from [development](https://github.com/Bannerlord-Coop-Team/BannerlordCoop)

## Related Issues

N/A

## Requirements

N/A

## Additional information

N/A

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

**Comment by samuelzurowski** [comment]
Another note: need to create a registry of the village on server startup.

**Comment by garrettluskey** [comment]
> need to create a registry of the village on server startup.

Fixed in #731
