### ISSUE TITLE
Increase Settlement Health Action

### ISSUE THREAD

**Issue by EgardA** [araex/BannerlordCoop#733]
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

IncreaseSettlementHealthAction is called on DailyTickSettlement, we want the DailyTickSettlement calculation to happen on server while the IncreaseSettlementHealthAction should happen on Client & Server.

## Intended Design

Server : DailyTickSettlement & IncreaseSettlementHealthAction
Client : IncreaseSettlementHealthAction

## Location

Create a branch based from [development](https://github.com/Bannerlord-Coop-Team/BannerlordCoop)
This should be in Settlement folder

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

**Comment by garrettluskey** [comment]
Rather we should just sync the setter for SettlementHitPoints. Lmk what you think, please close if you agree
