### ISSUE TITLE
SettlementComponent Sync

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#736]
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

Sync the following properties
- Owner
- Gold
- IsOwnerUnassigned

## Intended Design

Create necessary files in the GameInterface.Services.Settlement namespace/folder structure

## Location

Create a branch based from [development](https://github.com/Bannerlord-Coop-Team/BannerlordCoop)

## Related Issues

N/A

## Requirements

[HLR5](https://docs.google.com/document/d/1SAIUng44uFV3xKxJce7II9gGVJwOwvbyNkmYKxY-o8A/edit?usp=sharing)
[HLR6](https://docs.google.com/document/d/1SAIUng44uFV3xKxJce7II9gGVJwOwvbyNkmYKxY-o8A/edit?usp=sharing)
[HLR7](https://docs.google.com/document/d/1SAIUng44uFV3xKxJce7II9gGVJwOwvbyNkmYKxY-o8A/edit?usp=sharing)

## Additional information

N/A

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

**Comment by samuelzurowski** [comment]
Looks like:
- Gold
- IsOwnerUnassigned

may be the only ones required.

as Owner is handled in `settlement.ChangeOwnerOfSettlementAction`
