### ISSUE TITLE
Settlement Sync

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#737]
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

Go through all functions and disable ticking on client
Sync all of the items in the "Synced" section

**Key**
- Server side only (only allow the running of the function on the client side)
- Client side only (only allow the running of the function on the client side)
- Client side sync (request the server to change the value, server then changes the value and replies to the client allowing the change)
- Server side sync (only server allows running of the function and send to all clients the value changed and clients update the value/call original function)

**Synced**
- NumberOfEnemiesSpottedAround => Server side only 
- NumberOfAlliesSpottedAround => Server side only
- BribePaid => Server side sync
- SettlementHitPoints => Server side sync
- GarrisonWagePaymentLimit => Server side sync, client side sync allow for (OnUnlimitedWageToggled and OnCurrentWageLimitUpdated methods)
- LastAttackerParty => Server side sync
- LastThreatTime => Server side sync
- CurrentSiegeState => Server side sync
- Militia => Server side sync
- CollectNotablesToCache() => Server side sync
- AddHeroWithoutParty() => Server side sync
- RemoveHeroWithoutParty() => Server side sync
- AddMobileParty() => Server side sync
- RemoveMobileParty() => Server side sync
- SetWallSectionHitPointsRatioAtIndex() => Server side sync
- LastVisitTimeOfOwner => Server side sync using transpiler in EnterSettlementAction.ApplyInternal
- ClaimedBy => Client side sync using transpiler in conversation_player_ask_to_claim_land_answer_on_consequence()
- ClaimValue => Client side sync using transpiler in conversation_player_ask_to_claim_land_answer_on_consequence()
- CanBeClaimed => Server side sync using transpiler in SettlementClaimantCampaignBehavior.OnSettlementOwnerChanged()

**Deferred**
- _heroesWithoutPartyCache => Synced by AddHeroWithoutParty() and RemoveHeroWithoutParty()
- _partiesCache => Synced by AddMobileParty() and RemoveMobileParty()
- _settlementWallSectionHitPointsRatioList => Synced by SetWallSectionHitPointsRatioAtIndex()
- _readyMilitia => Synced by Militia
- _notablesCache => Synced by CollectNotablesToCache()
- _lastAttackerParty => Synced by LastAttackerParty
- _numberOfLordPartiesAt => Synced by AddMobileParty() and RemoveMobileParty()

**External Deferred**
- SiegeEvent => Synced by SeigeEvent
- MilitiaPartyComponent => Synced by MilitiaPartyComponent
- SettlementComponent => Synced by SettlementComponent #736
- SiegeEngines => Synced by SiegeEvent.SiegeEnginesContainer
- Alleys => Constant and synced by Alley
- Stash => Synced by ItemRoster
- Town => Synced by SettlementComponent #736
- Village => Synced by SettlementComponent #736
- Hideout => Synced by SettlementComponent #736
- SiegeStrategy => ISiegeEventSide.SetTactic()
- NumberOfTroopsKilledOnSide => Handled by TroopRoster.AddToCounts()

**Non-Synced**
- Party => Constant
- IsActive => Constant
- IsVisible => Nothing required
- IsInspected => Nothing required
- TaleWorlds.CampaignSystem.Map.ILocatable<TaleWorlds.CampaignSystem.Settlements.Settlement>.LocatorNodeIndex => Nothing required
- TaleWorlds.CampaignSystem.Map.ILocatable<TaleWorlds.CampaignSystem.Settlements.Settlement>.NextLocatable => Nothing required
- GatePosition => Constant
- Position2D => Constant
- CurrentNavigationFace => Constant
- Name => Constant
- EncyclopediaText => Constant
- LocationComplex => Constant
- StringId => Constant
- Id => Constant
- IsInitialized => Constant
- IsReady => Constant
- _boundVillages => Constant
- _name => Constant
- Culture => Constant
- _gatePosition => Constant
- _position => Constant
- _nextLocatable => Nothing required
- _locatorNodeIndex => Nothing required
- _isVisible => Nothing required
- HasVisited => Nothing required
- NumberOfLordPartiesTargeting => Nothing required
- _siegeEngineMissiles => Cosmetic so not required ISiegeEventSide.AddSiegeEngineMissile and ISiegeEventSide.RemoveDeprecatedMissiles

## Intended Design

Create necessary files in the GameInterface.Services.Settlement namespace/folder structure

## Location

Create a branch based from [development](https://github.com/Bannerlord-Coop-Team/BannerlordCoop)

## Related Issues

N/A

## Requirements

[HLR5](https://docs.google.com/document/d/1SAIUng44uFV3xKxJce7II9gGVJwOwvbyNkmYKxY-o8A/edit?usp=sharing)
[HLR6](https://docs.google.com/document/d/1SAIUng44uFV3xKxJce7II9gGVJwOwvbyNkmYKxY-o8A/edit?usp=sharing)
[HLR7](https://docs.google.com/document/d/1SAIUng44uFV3xKxJce7II9gGVJwOwvbyNkmYKxY-o8A/edit?usp=sharing)

## Additional information

N/A

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

**Comment by samuelzurowski** [comment]
WIP. So far done:

NumberOfEnemiesSpottedAround => Server side only
NumberOfAlliesSpottedAround => Server side only
BribePaid => Server side sync
SettlementHitPoints => Server side sync
LastAttackerParty => Server side sync
LastThreatTime => Server side sync
CurrentSiegeState => Server side sync
Militia => Server side sync

GarrisonWagePaymentLimit => Server side sync

Subscirbe issue in: client side sync allow for (OnUnlimitedWageToggled and OnCurrentWageLimitUpdated methods)
