### ISSUE TITLE
Army Join/Leave Sync

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#741]
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

1. Sync the values in the **Synced** list below.
2. Create an integration test for all values (1 for server changing the value and 1 for client changing the value if applicable)
3. Create a command to test changing the value in game [see similar command](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/blob/development/source/GameInterface/Services/Towns/Commands/TownDebugCommand.cs#L455)
4. Do not allow players to join Armies that contain other players, to determine this use the `IsPlayerParty` extension method for MobileParty
5. Add a TODO comment to add player interactions where step 4 was implemented

Also see additional information at the bottom for more information and templates

**Key**
Server side only (only allow the running of the function on the server side)
Client side only (only allow the running of the function on the client side)
Client side sync (request the server to change the value, server then changes the value and replies to the client allowing the change)
Server side sync (only server allows running of the function and send to all clients the value changed and clients update the value/call original function)

**Synced**
Army.OnAddPartyInternal() => Server side sync
Army.OnRemovePartyInternal() => Server side sync
MobileParty.Army (Setter) => Server side sync

**Deferred**
None

**Non-Synced**
None

## Intended Design

**Message networking**
![image](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/assets/15619189/48f5f821-8e8f-46cd-8d73-4c2547755aea)
**Integration Testing**
![image](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/assets/15619189/0e57923e-3af7-403a-aac3-aece50d7acb1)
## Location

Create a branch based from [development](https://github.com/Bannerlord-Coop-Team/BannerlordCoop)

## Related Issues

N/A

## Requirements

N/A

## Additional information

Using the [GameInterface Service Tempale](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/tree/development/source/GameInterface/Services/Template) create commands to test the synced values.

For network communication use [Server Service Template](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/tree/development/source/Coop.Core/Server/Services/Template) and [Client Service Template](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/tree/development/source/Coop.Core/Client/Services/Template)

It is recommended to start with an integration test, you can create one using the [test template](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/tree/development/source/Coop.IntegrationTests/Template).

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

**Comment by thomas-soutif** [comment]
The issue **cannot be finish totally** : It miss the sync of the army creation / deletion. 

From the server after I let the time pass : 
![image](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/assets/23268707/2ec553bf-a01a-4ec6-80d9-eafe25998425)

From the client : 
![image](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/assets/23268707/f45eb997-c1ac-4d78-9d48-154f3b7e9668)

I will finish to create the **code structur** and the **network messages and patches** for the futur, and it should works almost automatically when the army sync will be add

I'll also add a Todo where the modification should be done

**Comment by thomas-soutif** [comment]
Question about the MobileParty.Army (Setter) => Server side sync

![image](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/assets/23268707/4aa2f13f-2eb6-422c-b911-b6e0d620f924)

Is it really necessary ? I **synced** the 2 methods inside, **Army.OnAddPartyInternal()** and **Army.OnRemovePartyInternal()**,
so they trigger every time a mobileParty is add to an Army

I don't see the need to synch also this setter

**Comment by thomas-soutif** [comment]
We discuss with @EgardA about the army creation, and he suggest that we can sync the **Kingdom.CreateArmy** function to resolve the problem I mention before.
https://github.com/Bannerlord-Coop-Team/BannerlordCoop/issues/749

Waiting for this issue to be complete, before continuing this one. I will improve also the message construction, by using the ArmyName instead of the LeaderParty

**Comment by thomas-soutif** [comment]
Sync of adding partys working great
sync of removing party work almost, but only when I send a debug command 
When the game run and event occurs removing mobile party, I often have a NullReferenceException when I try to call the ```internal OnRemovePartyInternal()```.

**Comment by thomas-soutif** [comment]
Fixed :
 ```internal static void RemovePartyInternal(ref MobileParty mobileParty, Army army)```
the ref before MobileParty was creating a nullReferenceException
