### ISSUE TITLE
[Report] Null reference on TownGovernorPrefix

### ISSUE THREAD

**Issue by thomas-soutif** [araex/BannerlordCoop#744]
## Severity of issue/bug

- [ ] High
- [X ] Average
- [ ] Low

## Describe the issue/bug that appears (Image and/or text should work)

TownGovernorPrefix got a null value
![Screenshot from 2024-01-29 21-41-45 (1)](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/assets/23268707/09232b69-67c1-468a-92ff-4f3b18eebaa0)

I think it can happen with any function, could we maybe add a verification to check if the value is null ?

## Steps to reproduce

I just run the server , and then let the time pass in game for 1 minute

**Comment by EgardA** [comment]
Could it be that a town can lose its governor, thus being null? This issue occurs anyhow but this would change the fix, needs to be checked.

**Comment by thomas-soutif** [comment]
Yes it could be that, if it's the case, that mean the game send null references sometimes, and we could have the same issues for every object we get from the patch setter

**Comment by thomas-soutif** [comment]
The bug occurs again on my save, and after invesgiation, I found that the Town.governor can be null :

![image](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/assets/23268707/82952e34-dac5-4bb3-9bb2-87159fd4b217)

So yes, when a town governor is lost, the game set it to null. 
We should so add a verification that if the governor becomes null, we set for exemple in the TownGovernorChanged() Message, a empty string for the GovernorId field

**Comment by thomas-soutif** [comment]
Resolved the bug by adding a non nullable to the GovernordId, as the game accept it

When I tested it, it seem that the game sent a nullable for the governorId, before setting up again the hero 
![image](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/assets/23268707/527936b9-93bd-4952-9418-688af4026e11)

I've made test , everything ok, the function still patch correctly the town governor id when not null also
