### ISSUE TITLE
Town Auditor

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#747]
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

Create a class called TownAuditor that inherits the IHandler class, this class will send a message on the network
This audit message will contain
- All Town.StringId
- All town values that are meant to be synced by #738 (associated by Town.StringId)

Create a command that can only be called on the client that sends this message to the server

**Event Flow**
Command is called -> Command publishes event -> TownAuditor receives event -> TownAuditor packages data -> TownAuditor sends network message with packaged data -> on the server side TownAuditor receives this message -> TownAuditor compares all values -> TownAuditor logs value mismatches

## Intended Design

N/A

## Location

Create a branch based from [development](https://github.com/Bannerlord-Coop-Team/BannerlordCoop)

## Related Issues

N/A

## Requirements

N/A

## Additional information

N/A

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

**Comment by thomas-soutif** [comment]
Is this feature is to detect the incoherences between the clients and the server for the towns ? How frequent should it be called automatically or maybe we keep it manually with only the Command?

**Comment by EgardA** [comment]
Call it once when the game has been loaded, towns don't change during runtime

**Comment by garrettluskey** [comment]
> Is this feature is to detect the incoherences between the clients and the server for the towns?

Exactly

> How frequent should it be called automatically or maybe we keep it manually with only the Command?

Only commands, we can worry about automation after
