### ISSUE TITLE
Remove Reflection in favor of Member publicize 

### ISSUE THREAD

**Issue by samuelzurowski** [araex/BannerlordCoop#772]
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description
Before Publicize was used all members were set via reflection (e.g. Extensions folder)

## Intended Design
Find all patches and change to use Publicizer members rather then reflection.

## Location

Create a branch based from [development](https://github.com/Bannerlord-Coop-Team/BannerlordCoop)

**Comment by MaxDorob** [comment]
I'll do that
