### ISSUE TITLE
[ISSUE] Clans not being added to object manager

### ISSUE THREAD

**Issue by EgardA** [araex/BannerlordCoop#820]
# For New Contributors
[How to contribute](https://github.com/Bannerlord-Coop-Team/BannerlordCoop/wiki/Getting-Started-as-a-Contributor)

## Description

Clans are currently not being added to the object manager

## Intended Design

Clans being added to the object manager

## Location

Create a branch based from [development](https://github.com/Bannerlord-Coop-Team/BannerlordCoop)

## Definition of Done
- [ ] Class level comments exist for all new classes.
- [ ] XUnit tests exist for every method that does not require the game to be ran.

**Comment by martinprejsa** [comment]
Is this a server or a client issue?

**Comment by EgardA** [comment]
A both issue, there's no place they are added. There's a list for it so I would guess the idea is to have it in there.
