### ISSUE TITLE
TaleWorlds.CampaignSystem.Actions Synchronization

### ISSUE THREAD

**Issue by araex** [araex/BannerlordCoop#93]
These should be synchronized. @garrettluskey wrote all the serializers, i prepared patch generators & an RPC module. With these components most of the actions should be quite easy to synchronize. I'm fairly certain that most of it should be just a few lines of relatively simple code. I'll synchronize a couple of actions myself as an example.

**Comment by garrettluskey** [comment]
Keep in mind that these actions may be invoked by internal functions that we may have to intercept instead.

**Comment by araex** [comment]
You are right, synchronizing the `TaleWorlds.CampaignSystem.CampaignEvents` is probably a better approach since it is less intrusive. Most events would probably be controlled by the host only. But if we get those synced, the `CampaignBehavior` are synced as well, as Events are the only way those seem to get triggered. Which in turn covers about 90% of all `Action` usages.

**Comment by araex** [comment]
That might have been a bit optimistic :) It's all interwoven:
![Action-Behaviour interaction](https://raw.githubusercontent.com/wiki/Bannerlord-Coop-Team/BannerlordCoop/img/Actions.svg)

Not yet sure how to tackle this.
