### ISSUE TITLE
Investigate how the game map is handled when host enters town/battle

### ISSUE THREAD

**Issue by garrettluskey** [araex/BannerlordCoop#94]
The game map may be unloaded on the host when the host party enters a town/battle. The map may remain loaded but remain paused. Find out the case using dnspy and comment on this issue with a verdict.

**Comment by Jvansant122** [comment]
Game map might be unloaded. I tested on unmodded local except for a harmony patch to set the speed to fastforward at all times, the game map did not progress while I was in combat. Going to test further.

**Comment by garrettluskey** [comment]
A few questions come up with this.

1. Can there be multiple active states?
2. Is it possible to keep the state running while in the background?

**Comment by garrettluskey** [comment]
Map stops simulating when host is in another state. Fixed with dedicated server.
